name: Community docsite CI

on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nox-sessions:
    uses: ./.github/workflows/reusable-nox.yml
  pre-commit:
    uses: ./.github/workflows/reusable-pre-commit.yml
